namespace SvSim.SlangAstParser.AstTree.SvEnums;
[Flags]
public enum SvAstFlags : ulong
{
    None = 0,
    InsideConcatenation = 1ul << 0,
    UnevaluatedBranch = 1ul << 1,
    AllowDataType = 1ul << 2,
    AssignmentAllowed = 1ul << 3,
    AssignmentDisallowed = 1ul << 4,
    NonProcedural = 1ul << 5,
    StaticInitializer = 1ul << 6,
    StreamingAllowed = 1ul << 7,
    TopLevelStatement = 1ul << 8,
    AllowUnboundedLiteral = 1ul << 9,
    AllowUnboundedLiteralArithmetic = 1ul << 10,
    Function = 1ul << 11,
    Final = 1ul << 12,
    NonBlockingTimingControl = 1ul << 13,
    EventExpression = 1ul << 14,
    AllowTypeReferences = 1ul << 15,
    AssertionExpr = 1ul << 16,
    AllowClockingBlock = 1ul << 17,
    AssertionInstanceArgCheck = 1ul << 18,
    AssertionDelayOrRepetition = 1ul << 19,
    LValue = 1ul << 20,
    PropertyNegation = 1ul << 21,
    PropertyTimeAdvance = 1ul << 22,
    RecursivePropertyArg = 1ul << 23,
    ConcurrentAssertActionBlock = 1ul << 24,
    AllowCoverageSampleFormal = 1ul << 25,
    AllowCoverpoint = 1ul << 26,
    AllowNetType = 1ul << 27,
    OutputArg = 1ul << 28,
    AllowInterconnect = 1ul << 29,
    StreamingWithRange = 1ul << 30,
    SpecifyBlock = 1ul << 31,
    SpecparamInitializer = 1ul << 32,
    DPIArg = 1ul << 33,
    AssertionDefaultArg = 1ul << 34,
    LAndRValue = 1ul << 35,
    NoReference = 1ul << 36,
    ConfigParam = 1ul << 37,
    TypeOperator = 1ul << 38,
    ForkJoinAnyNone = 1ul << 39,
    DisallowUDNT = 1ul << 40,
    BindInstantiation = 1ul << 41,
    WildcardPortConn = 1ul << 42
}