namespace SvSim.SlangAstParser.AstTree.SvEnums;

public enum SvTypeKind
{
    PredefinedIntegerType,
    ScalarType,
    FloatingType,
    EnumType,
    PackedArrayType,
    FixedSizeUnpackedArrayType,
    DynamicArrayType,
    DPIOpenArrayType,
    AssociativeArrayType,
    QueueType,
    PackedStructType,
    UnpackedStructType,
    PackedUnionType,
    UnpackedUnionType,
    ClassType,
    CovergroupType,
    VoidType,
    NullType,
    CHandleType,
    StringType,
    EventType,
    UnboundedType,
    TypeRefType,
    UntypedType,
    SequenceType,
    PropertyType,
    VirtualInterfaceType,
    TypeAlias,
    ErrorType,
    ForwardingTypedef,
    NetType,
}